# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and deploy to staging server by Copying the artifacts using ssh to play.dev.grid.tf

name: CI/CD pipeline 

on:
  release:
    types: [published]

concurrency:
  # one instance of runing pipeline allowed per branch.
  # On master, we want all builds to complete even if merging happens faster for better reliability and to make it easier to discover at which point something broke.
  # on developmetn, new workflow trigger will cancel the in progress job, and start a new one..
  group: ${{ format('ci-{0}', github.ref) }}
  cancel-in-progress: ${{ github.event_name == 'release' && github.event.release.prerelease == false }}
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Build in case development
      if: ${{ github.ref == 'refs/heads/development' }}
      run: |
        VERSION=$GITHUB_SHA
        VERSION=${VERSION:0:7} NETWORK=dev yarn build:app

    - name: Build in case test
      if: |
        github.event.release.prerelease == true &&
        contains(github.event.release.tag_name, 'rc')
      run: | 
        echo test

    - name: Build in case qa
      if: |
        github.event.release.prerelease == true &&
        contains(github.event.release.tag_name, 'qa')
      run: | 
        echo qa

    - name: Build in case main
      if: | 
        github.event_name == 'release' &&
        github.event.release.prerelease != true   
      run: |
        echo main
